#!/bin/bash
# This file calls the Python preprocessing logic for each `.csv` input file.
# Load the global variables.
source CONSTANTS.sh

#$1=The path to the input statement, e.g. import/john/mybank/savings/1-in/2018/123456789_2018-06-30.csv
INPUT_CSV_FILEPATH=$1

# $2=The path to an output file that can be sent to hledger, e.g. import/john/mybank/savings/2-preprocessed/2018/123456789_2018-06-30.csv
OUTPUT_CSV_FILEPATH=$2

# $3=The name of the bank, e.g. mybank
BANK_NAME=$3

# $4=The type of the account, e.g. savings
ACCOUNT_TYPE=$4

# $5=The name of the owner, e.g. john
ACCOUNT_HOLDER=$5

# TODO: include hledger_preprocessor call to create rules.
CREATE_RULES_COMMAND="hledger_preprocessor --start-path $PWD --generate-rules --account-holder $ACCOUNT_HOLDER --bank $BANK_NAME --account-type $ACCOUNT_TYPE"

CONSTRUCTION_LOGFILENAME="construct_output.log"

echo "INPUT_CSV_FILEPATH=$INPUT_CSV_FILEPATH" > "$CONSTRUCTION_LOGFILENAME"
echo "OUTPUT_CSV_FILEPATH=$OUTPUT_CSV_FILEPATH" >> "$CONSTRUCTION_LOGFILENAME"
echo "BANK_NAME=$BANK_NAME" >> "$CONSTRUCTION_LOGFILENAME"
echo "ACCOUNT_TYPE=$ACCOUNT_TYPE" >> "$CONSTRUCTION_LOGFILENAME"
echo "ACCOUNT_HOLDER=$ACCOUNT_HOLDER" >> "$CONSTRUCTION_LOGFILENAME"

echo "PWD=$PWD" >> "$CONSTRUCTION_LOGFILENAME"
echo "PREPROCESSING_DIR=$PREPROCESSING_DIR" >> "$CONSTRUCTION_LOGFILENAME"
echo "RAW_INPUT_DIR=$RAW_INPUT_DIR" >> "$CONSTRUCTION_LOGFILENAME"
echo "PREPROCESSED_OUTPUT_DIR=$PREPROCESSED_OUTPUT_DIR" >> "$CONSTRUCTION_LOGFILENAME"
echo "JOURNAL_OUTPUT_DIR=$JOURNAL_OUTPUT_DIR" >> "$CONSTRUCTION_LOGFILENAME"


echo "CREATE_RULES_COMMAND=$CREATE_RULES_COMMAND" >> "$CONSTRUCTION_LOGFILENAME"